{"name": "Departamento Cadastrado com Sucesso -- @1.1 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=88.0.4324.182)\n\n", "trace": "  File \"C:\\Users\\danieltorresdev\\AppData\\Roaming\\Python\\Python39\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\danieltorresdev\\AppData\\Roaming\\Python\\Python39\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\CadastroDepartamento.py\", line 28, in step_impl\n    departamento(context).verificar_msg(texto)\n  File \"C:\\Users\\danieltorresdev\\Documents\\Workspaces\\WorkspaceResidenciaIMD\\testeCRUD\\cursosDotNetCore\\Angular10dotNETCoreAPI\\angular10\\test\\Behave Project\\features\\pages\\departamento.py\", line 33, in verificar_msg\n    alert = wait.until(expected_conditions.alert_is_present())\n  File \"c:\\python39\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 71, in until\n    value = method(self._driver)\n  File \"c:\\python39\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 401, in __call__\n    alert = driver.switch_to.alert\n  File \"c:\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\switch_to.py\", line 55, in alert\n    alert.text\n  File \"c:\\python39\\lib\\site-packages\\selenium\\webdriver\\common\\alert.py\", line 67, in text\n    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)[\"value\"]\n  File \"c:\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Dado que esteja na página inicial do CRUD", "status": "passed", "start": 1614106028301, "stop": 1614106029837}, {"name": "Quando seleciono a opção Departamento", "status": "passed", "start": 1614106029837, "stop": 1614106030043}, {"name": "E seleciono Adicionar Departamento", "status": "passed", "start": 1614106030044, "stop": 1614106030137}, {"name": "E insiro testeAuto no campo Nome do Add Department", "status": "passed", "start": 1614106030138, "stop": 1614106030904}, {"name": "E clico no botão Adicionar", "status": "passed", "start": 1614106030905, "stop": 1614106030976}, {"name": "Então verifico que a mensagem Added Successfully é exibida", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=88.0.4324.182)\n\n", "trace": "  File \"C:\\Users\\danieltorresdev\\AppData\\Roaming\\Python\\Python39\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\danieltorresdev\\AppData\\Roaming\\Python\\Python39\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\CadastroDepartamento.py\", line 28, in step_impl\n    departamento(context).verificar_msg(texto)\n  File \"C:\\Users\\danieltorresdev\\Documents\\Workspaces\\WorkspaceResidenciaIMD\\testeCRUD\\cursosDotNetCore\\Angular10dotNETCoreAPI\\angular10\\test\\Behave Project\\features\\pages\\departamento.py\", line 33, in verificar_msg\n    alert = wait.until(expected_conditions.alert_is_present())\n  File \"c:\\python39\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 71, in until\n    value = method(self._driver)\n  File \"c:\\python39\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 401, in __call__\n    alert = driver.switch_to.alert\n  File \"c:\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\switch_to.py\", line 55, in alert\n    alert.text\n  File \"c:\\python39\\lib\\site-packages\\selenium\\webdriver\\common\\alert.py\", line 67, in text\n    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)[\"value\"]\n  File \"c:\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1614106030977, "stop": 1614106056636}], "parameters": [{"name": "nomeDepartamento", "value": "testeAuto"}], "start": 1614106028250, "stop": 1614106068799, "uuid": "1e9ba385-c8ed-4a1d-b472-64ab46c06c91", "historyId": "08b927332f6308495961ea8a350c0510", "fullName": "Cadastrar um Departamento: Departamento Cadastrado com Sucesso", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "TC0000_01"}, {"name": "tag", "value": "all"}, {"name": "tag", "value": "departamento"}, {"name": "tag", "value": "departamentoSucesso"}, {"name": "tag", "value": "sprintTeste"}, {"name": "feature", "value": "Cadastrar um Departamento"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}